/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combined;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import kelly8282.flappybird.*;
import java.awt.Component;
import javax.swing.JFrame;
import minesweeper.*;
import tictactoe.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author elainewang
 */
public class mainScreen extends javax.swing.JPanel {

	JFrame frame;


	public static void main(String[] args)
	{
		mainScreen screen = new mainScreen();
	}

    /**
     * Creates new form mainScreen
     */
    public mainScreen() {
		((Component) this).setFocusable(true);
		frame = new JFrame("Main");
		frame.setSize(600, 300);
		frame.add(this);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
		
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FlappyBird = new javax.swing.JButton();
        TicTacToe = new javax.swing.JButton();
        Minesweeper = new javax.swing.JButton();

        FlappyBird.setText("Flappy Bird");
        FlappyBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlappyBirdActionPerformed(evt);
            }
        });

        TicTacToe.setText("Tic Tac Toe");
        TicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeActionPerformed(evt);
            }
        });

        Minesweeper.setText("Minesweeper");
        Minesweeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinesweeperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(FlappyBird)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TicTacToe)
                .addGap(18, 18, 18)
                .addComponent(Minesweeper)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlappyBird)
                    .addComponent(TicTacToe)
                    .addComponent(Minesweeper))
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TicTacToeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeActionPerformed
        // TODO add your handling code here:
        //rebekah
        new InitialScreen();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Game().setVisible(true);
            }
        });

    }//GEN-LAST:event_TicTacToeActionPerformed

    private void MinesweeperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinesweeperActionPerformed
       //elaine
        try {
            // TODO add your handling code here:
            Play run = new Play();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MinesweeperActionPerformed

    private void FlappyBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlappyBirdActionPerformed
        // TODO add your handling code here:
        //kelly
        System.out.println("Starting Flappy Bird - 1.1 by Kelly");
        frame.setVisible(false);
        FlappyBird flappyBird = new FlappyBird();
        flappyBird.addWindowListener(new WindowAdapter() {
        	public void windowClosing(WindowEvent we) {
        		frame.setVisible(true);
        		flappyBird.dispose();
        	}
        });
    }//GEN-LAST:event_FlappyBirdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlappyBird;
    private javax.swing.JButton Minesweeper;
    private javax.swing.JButton TicTacToe;
    // End of variables declaration//GEN-END:variables
}
