/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combined;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import kelly8282.flappybird.*;
import java.awt.Component;
import javax.swing.JFrame;
import minesweeper.*;
import tictactoe.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;

/**
 *
 * @author elainewang
 */
public class mainScreen extends javax.swing.JPanel {

	JFrame frame;


	public static void main(String[] args)
	{
		mainScreen screen = new mainScreen();
	}

    /**
     * Creates new form mainScreen
     */
    public mainScreen() {
    	setBackground(Color.BLACK);
		((Component) this).setFocusable(true);
		frame = new JFrame("Main");
		frame.getContentPane().setBackground(Color.BLACK);
		frame.setBackground(Color.BLACK);
		frame.setSize(600, 300);
		frame.getContentPane().add(this);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
		
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FlappyBird = new javax.swing.JButton();
        FlappyBird.setBackground(Color.WHITE);
        FlappyBird.setForeground(Color.YELLOW);
        FlappyBird.setFont(new Font("Silom", Font.PLAIN, 20));
        TicTacToe = new javax.swing.JButton();
        TicTacToe.setVerticalAlignment(SwingConstants.TOP);
        TicTacToe.setFont(new Font("Adobe Garamond Pro", Font.PLAIN, 20));
        Minesweeper = new javax.swing.JButton();
        Minesweeper.setFont(new Font("Chalkduster", Font.PLAIN, 20));
        Minesweeper.setForeground(Color.RED);

        FlappyBird.setText("FLAPPY BIRD");
        FlappyBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlappyBirdActionPerformed(evt);
            }
        });

        TicTacToe.setText("TICTACTOE");
        TicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeActionPerformed(evt);
            }
        });

        Minesweeper.setText("MINESWEEPER");
        Minesweeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinesweeperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(15)
        			.addComponent(FlappyBird, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(TicTacToe, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Minesweeper, GroupLayout.PREFERRED_SIZE, 198, Short.MAX_VALUE)
        			.addGap(15))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(118, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(FlappyBird)
        				.addComponent(TicTacToe, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Minesweeper, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        			.addGap(122))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void TicTacToeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeActionPerformed
        // TODO add your handling code here:
        //rebekah
        InitialScreen initialScreen = new InitialScreen();
        frame.setVisible(false);
        
        initialScreen.window.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent we) {
                            frame.setVisible(true);
                            //initialScreen.dispose();
                    }
                });
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Game().setVisible(true);
              
            }
            
        });
        
        

    }//GEN-LAST:event_TicTacToeActionPerformed

    private void MinesweeperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinesweeperActionPerformed
       //elaine
        try {
            // TODO add your handling code here:
            frame.setVisible(false);
            Play minesweeper = new Play();
            minesweeper.addWindowListener(new WindowAdapter() {
        	public void windowClosing(WindowEvent we) {
        		frame.setVisible(true);
        		minesweeper.dispose();
        	}
        });
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MinesweeperActionPerformed

    private void FlappyBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlappyBirdActionPerformed
        // TODO add your handling code here:
        //kelly
        System.out.println("Starting Flappy Bird - 1.1 by Kelly");
        frame.setVisible(false);
        FlappyBird flappyBird = new FlappyBird();
        flappyBird.addWindowListener(new WindowAdapter() {
        	public void windowClosing(WindowEvent we) {
        		frame.setVisible(true);
        		flappyBird.dispose();
        	}
        });
    }//GEN-LAST:event_FlappyBirdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlappyBird;
    private javax.swing.JButton Minesweeper;
    private javax.swing.JButton TicTacToe;
    // End of variables declaration//GEN-END:variables
}
