/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combined;

/**
 *
 * @author elainewang
 */
public class mainScreen extends javax.swing.JPanel {

    /**
     * Creates new form mainScreen
     */
    public mainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FlappyBird = new javax.swing.JButton();
        TicTacToe = new javax.swing.JButton();
        Minesweeper = new javax.swing.JButton();

        FlappyBird.setText("jButton1");
        FlappyBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlappyBirdActionPerformed(evt);
            }
        });

        TicTacToe.setText("jButton2");
        TicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeActionPerformed(evt);
            }
        });

        Minesweeper.setText("Minesweeper");
        Minesweeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinesweeperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(FlappyBird)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(TicTacToe)
                .addGap(18, 18, 18)
                .addComponent(Minesweeper)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlappyBird)
                    .addComponent(TicTacToe)
                    .addComponent(Minesweeper))
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TicTacToeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicTacToeActionPerformed

    private void MinesweeperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinesweeperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinesweeperActionPerformed

    private void FlappyBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlappyBirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlappyBirdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlappyBird;
    private javax.swing.JButton Minesweeper;
    private javax.swing.JButton TicTacToe;
    // End of variables declaration//GEN-END:variables
}
